### ISSUE TITLE
Clone vortan_webapp and get it running locally

### ISSUE THREAD

**Issue by sourencho** [DataPoint-Armenia/vortan_webapp#1]
There should be instructions in the repo readme: https://github.com/DataPoint-Armenia/vortan_webapp

The repo will hit the heroku app by default.
You also have the option to run the [vortan_api](https://github.com/DataPoint-Armenia/vortan_api) locally and hit that by changing the url [here](https://github.com/DataPoint-Armenia/vortan_webapp/blob/main/frontend/src/components/InputForm.jsx#L37)

**Comment by tado-mi** [comment]
success!
