### ISSUE TITLE
Make input box bigger and allow user to get suggestions for a list of words

### ISSUE THREAD

**Issue by sourencho** [DataPoint-Armenia/vortan_webapp#3]
The [vortan_api](https://github.com/DataPoint-Armenia/vortan_api) `suggest` endpoint will return suggestions for arbitrary length text if you set the `mode` param to `tokenize` (see https://github.com/DataPoint-Armenia/vortan_api/blob/main/spellchecker_app/routes.py#L22). You can send many sentences and it will return suggestions for each word individually.

**Comment by tado-mi** [comment]
@sourencho 
the max width of the `<Main />` component is defined to be 400px. Is that intentional?

**Comment by sourencho** [comment]
It was just an easy way to make it look nice in the demo. Not very intentional - Feel free to change it 
Ideally it would be responsive but also feel nice on a wide screen

**Comment by tado-mi** [comment]
@sourencho 
one more question - when you say "allow user to get suggestions for a list of words", you mean other than how that happens now? do you mean to change how the output is displayed, or how the input is processed? or something else?

**Comment by sourencho** [comment]
I guess the current functionality already supports this!
No need to do much else here.
